services:
    php:
        build: .docker/php
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached

    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php

    redis:
        image: redis:latest
        command: redis-server --appendonly yes
        volumes:
        - .docker/redis/data:/data
        ports:
        - 6379:6379

    db:
     image: postgres:16
     ports:
         - 5432:5432
     volumes:
         - .docker/db/data:/var/lib/postgresql/data
         - .docker/db/sql:/docker-entrypoint-initdb.d
     environment:
         - POSTGRES_USER=laravel
         - POSTGRES_PASSWORD=laravel
         - POSTGRES_DB=laravel
